# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c20578a0b8f6f78a029ef5a64924aa5b0178a0382f7d3b01587d9b08136c0ac630a2b25f13a580447c2527c088bd423288569d53e91be7cfee72725e44b6108

test:
  secret_key_base: 4360f3575afce9724314c27f5e734fd6d5c35f8b4c5419f5f4b9757111927991e0f2a04e81fa4a6a91902fc86f302d88c2bec5a22b5ef051f4c1d154d8715a0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
